codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    project:
      default:
        target: 0%
        threshold: 5%
        patch: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true
