apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test-front
  namespace: default
  labels:
    app: gke-test-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gke-test-front
  template:
    metadata:
      labels:
        app: gke-test-front
    spec:
      containers:
        - name: gke-test-front
          image: gcr.io/PROJECT_ID/IMAGE_FRONT:TAG
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
        - name: gke-test-front-2
          image: gcr.io/PROJECT_ID/IMAGE_FRONT:TAG
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gke-test-front-hpa-zs1p
  namespace: default
  labels:
    app: gke-test-front
spec:
  scaleTargetRef:
    kind: Deployment
    name: gke-test-front
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
