name: CI/CDelivery to GitHub Container Registry

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FRONT_IMAGE_NAME: frontend
  BACK_IMAGE_NAME: backend

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and test front
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Lowercase repository name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Short the sha to 7 characters only
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::7})

      - name: build and push front app
        id: front_build_and_push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}/${{ env.FRONT_IMAGE_NAME }}:${{ steps.vars.outputs.tag }}

      - name: Front image digest
        run: echo ${{ steps.front_build_and_push.outputs.digest }}

      - name: build and push back app
        id: back_build_and_push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ env.REPO }}/${{ env.BACK_IMAGE_NAME }}:${{ steps.vars.outputs.tag }}

      - name: Back image digest
        run: echo ${{ steps.back_build_and_push.outputs.digest }}
